name: test_build_kannan_svn
svn: https://src.chromium.org/chrome/trunk/src/chrome/common/extensions/docs/examples/tutorials/getstarted/
ref: master
shell_command:
 - echo "first echo"
 - sleep 10
 - echo "second echo"
 - sleep 5
